#!/bin/bash
#shell script
EMAIL=abc@me.com
PASSWORD=123

BASE_URL="10.13.105.91:3000"
URL="${BASE_URL}/sign-up"
#URL="http://httpbin.org/post"

url() {

  CONTENT_TYPE="application/x-www-form-urlencoded"

  curl ${URL} \
   --include \
   --request POST \
   --header "Content-Type: ${CONTENT_TYPE}" \
   --data-urlencode "credentials[email]=${EMAIL}" \
   --data-urlencode "credentials[password]=${PASSWORD}"

}

json() {

  CONTENT_TYPE="application/json"

  curl ${URL} \
  --include \
  --request POST \
  --header "Content-Type: ${CONTENT_TYPE}" \
  --data "{
    \"credentials\": {
      \"email\": \"${EMAIL}\",
      \"password\": \"${PASSWORD}\"
    }
  }"

}



json

echo
